#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;

require_once __DIR__ . '/bootstrap.php';

// start console application
$app = new Application;
$app->add($container->make('FetchProductsCommand'));
$app->run();
